blank_issues_enabled: false
contact_links:
  - name: Discord Support Server
    url: https://discord.gg/rdjpS2K8hC
    about: Ask questions, receive support, and discuss with the community in D4's FiveM Hub.
